//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace DayloaderClock.Resources;

using System.Globalization;
using System.Resources;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
public class Strings
{
    private static ResourceManager? resourceMan;
    private static CultureInfo? resourceCulture;

    /// <summary>Returns the cached ResourceManager instance used by this class.</summary>
    public static ResourceManager ResourceManager
    {
        get
        {
            if (resourceMan is null)
            {
                resourceMan = new ResourceManager("DayloaderClock.Resources.Strings",
                    typeof(Strings).Assembly);
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    public static CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    private static string GetString(string name) =>
        ResourceManager.GetString(name, resourceCulture) ?? name;

    // ── MainWindow ────────────────────────────────────────────
    public static string AppTitle => GetString("AppTitle");
    public static string Tooltip_EndDay => GetString("Tooltip_EndDay");
    public static string Tooltip_Pause => GetString("Tooltip_Pause");
    public static string Tooltip_History => GetString("Tooltip_History");
    public static string Tooltip_Settings => GetString("Tooltip_Settings");
    public static string Tooltip_Minimize => GetString("Tooltip_Minimize");
    public static string Tooltip_Hide => GetString("Tooltip_Hide");
    public static string Tooltip_Resume => GetString("Tooltip_Resume");
    public static string Tooltip_ResumeDay => GetString("Tooltip_ResumeDay");
    public static string Tooltip_Pomodoro => GetString("Tooltip_Pomodoro");
    public static string Tooltip_StopPomodoro => GetString("Tooltip_StopPomodoro");

    public static string StartTime => GetString("StartTime");
    public static string StartTimeDefault => GetString("StartTimeDefault");
    public static string Remaining => GetString("Remaining");
    public static string RemainingDefault => GetString("RemainingDefault");
    public static string Finished => GetString("Finished");
    public static string Overtime => GetString("Overtime");
    public static string LunchPause => GetString("LunchPause");
    public static string DayCompleted => GetString("DayCompleted");
    public static string Paused => GetString("Paused");

    public static string Mini_Done => GetString("Mini_Done");
    public static string Mini_Stop => GetString("Mini_Stop");
    public static string Mini_Paused => GetString("Mini_Paused");
    public static string Mini_Normal => GetString("Mini_Normal");

    // ── System Tray ───────────────────────────────────────────
    public static string Tray_Show => GetString("Tray_Show");
    public static string Tray_MiniMode => GetString("Tray_MiniMode");
    public static string Tray_EndDay => GetString("Tray_EndDay");
    public static string Tray_Pause => GetString("Tray_Pause");
    public static string Tray_Resume => GetString("Tray_Resume");
    public static string Tray_Pomodoro => GetString("Tray_Pomodoro");
    public static string Tray_StopPomodoro => GetString("Tray_StopPomodoro");
    public static string Tray_ResetDay => GetString("Tray_ResetDay");
    public static string Tray_History => GetString("Tray_History");
    public static string Tray_Settings => GetString("Tray_Settings");
    public static string Tray_Quit => GetString("Tray_Quit");

    // ── Messages / Notifications ──────────────────────────────
    public static string Msg_ResetConfirm => GetString("Msg_ResetConfirm");
    public static string Msg_OvertimeStarted => GetString("Msg_OvertimeStarted");
    public static string Msg_PomodoroFocus => GetString("Msg_PomodoroFocus");
    public static string Msg_PomodoroCompleted => GetString("Msg_PomodoroCompleted");
    public static string Msg_PomodoroBreak => GetString("Msg_PomodoroBreak");

    // ── Settings Window ───────────────────────────────────────
    public static string Settings_Title => GetString("Settings_Title");
    public static string Settings_Header => GetString("Settings_Header");
    public static string Settings_WorkDayHours => GetString("Settings_WorkDayHours");
    public static string Settings_LunchStart => GetString("Settings_LunchStart");
    public static string Settings_LunchDuration => GetString("Settings_LunchDuration");
    public static string Settings_AutoStart => GetString("Settings_AutoStart");
    public static string Settings_PomodoroDuration => GetString("Settings_PomodoroDuration");
    public static string Settings_PomodoroDnd => GetString("Settings_PomodoroDnd");
    public static string Settings_Cancel => GetString("Settings_Cancel");
    public static string Settings_Save => GetString("Settings_Save");
    public static string Settings_Language => GetString("Settings_Language");
    public static string Settings_RestartRequired => GetString("Settings_RestartRequired");
    public static string Settings_Error_WorkHours => GetString("Settings_Error_WorkHours");
    public static string Settings_Error_LunchStart => GetString("Settings_Error_LunchStart");
    public static string Settings_Error_LunchDuration => GetString("Settings_Error_LunchDuration");
    public static string Settings_Error_Pomodoro => GetString("Settings_Error_Pomodoro");
    public static string Settings_Error_Title => GetString("Settings_Error_Title");

    // ── History Window ────────────────────────────────────────
    public static string History_Title => GetString("History_Title");
    public static string History_Header => GetString("History_Header");
    public static string History_Days => GetString("History_Days");
    public static string History_Total => GetString("History_Total");
    public static string History_Average => GetString("History_Average");
    public static string History_ExportCsv => GetString("History_ExportCsv");
    public static string History_ExportXlsx => GetString("History_ExportXlsx");
    public static string History_Tooltip => GetString("History_Tooltip");
    public static string History_CsvDialogTitle => GetString("History_CsvDialogTitle");
    public static string History_XlsxDialogTitle => GetString("History_XlsxDialogTitle");
    public static string History_ExportSuccess => GetString("History_ExportSuccess");
    public static string History_ExportTitle => GetString("History_ExportTitle");
    public static string History_ExportError => GetString("History_ExportError");
    public static string History_ErrorTitle => GetString("History_ErrorTitle");
    public static string History_Yes => GetString("History_Yes");
    public static string History_No => GetString("History_No");

    // Day abbreviations
    public static string Day_Mon => GetString("Day_Mon");
    public static string Day_Tue => GetString("Day_Tue");
    public static string Day_Wed => GetString("Day_Wed");
    public static string Day_Thu => GetString("Day_Thu");
    public static string Day_Fri => GetString("Day_Fri");
    public static string Day_Sat => GetString("Day_Sat");
    public static string Day_Sun => GetString("Day_Sun");

    // Export column headers
    public static string Export_Date => GetString("Export_Date");
    public static string Export_Login => GetString("Export_Login");
    public static string Export_LastActivity => GetString("Export_LastActivity");
    public static string Export_MinutesWorked => GetString("Export_MinutesWorked");
    public static string Export_HoursWorked => GetString("Export_HoursWorked");
    public static string Export_DayComplete => GetString("Export_DayComplete");
    public static string Export_LunchMinutes => GetString("Export_LunchMinutes");
    public static string Export_SheetName => GetString("Export_SheetName");

    // Messages
    public static string Msg_AlreadyRunning => GetString("Msg_AlreadyRunning");
}
